//@ui5-bundle ui5/walkthrough/Component-preload.js
sap.ui.predefine("ui5/walkthrough/Component", ["sap/ui/core/UIComponent","sap/ui/model/json/JSONModel"],(e,t)=>{"use strict";return e.extend("ui5.walkthrough.Component",{metadata:{interfaces:["sap.ui.core.IAsyncContentCreation"],manifest:"json"},init(){e.prototype.init.apply(this,arguments);const n={recipient:{name:"klientów"}};const i=new t(n);this.setModel(i)}})});
sap.ui.predefine("ui5/walkthrough/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("ui5.walkthrough.controller.App",{})});
sap.ui.predefine("ui5/walkthrough/controller/StartPanel.controller", ["sap/ui/core/mvc/Controller","sap/m/MessageToast","sap/ui/model/odata/v2/ODataModel"],(e,t,o)=>{"use strict";return e.extend("ui5.walkthrough.controller.StartPanel",{onInit(){const e=new o("http://localhost:8080/odata/Northwind.svc");this.getView().setModel(e)},onShowClients(){const e=this.getView().getModel("i18n").getResourceBundle();const o=this.getView().getModel().getProperty("/recipient/name");const s=e.getText("dataMsg",[o]);t.show(s)}})});
sap.ui.require.preload({
	"ui5/walkthrough/i18n/i18n.properties":'# Deskryptor aplikacji\r\nappTitle=Zadanie rekrutacyjne programista Javascript\r\nappDescription=Aplikacja z danymi klient\\u00f3w w tabeli\r\n\r\n# Panel\r\nshowDataButtonText=Dane klient\\u00f3w\r\ndataMsg=Dane {0}\r\nshowTitleText=Zadanie rekrutacyjne TOYA S.A.\r\nfirstPageTitle=1 widok',
	"ui5/walkthrough/i18n/i18n_en.properties":'# Deskryptor aplikacji\r\nappTitle=Javascript programmer recruitment task\r\nappDescription=Application with customer data in a table\r\n\r\n# Panel\r\nshowDataButtonText=Clients\r\ndataMsg=Data {0}\r\nshowTitleText=Recruitment task TOYA S.A.\r\nfirstPageTitle=1 view',
	"ui5/walkthrough/i18n/i18n_pl_PL.properties":'# Deskryptor aplikacji\r\nappTitle=Zadanie rekrutacyjne programista Javascript\r\nappDescription=Aplikacja z danymi klient\\u00f3w w tabeli\r\n\r\n# Panel\r\nshowDataButtonText=Dane klient\\u00f3w\r\ndataMsg=Dane {0}\r\nshowTitleText=Zadanie rekrutacyjne TOYA S.A.\r\nfirstPageTitle=1 widok',
	"ui5/walkthrough/manifest.json":'{"_version":"1.71.70","sap.app":{"id":"ui5.walkthrough","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":["","en","pl_PL"]},"supportedLocales":["pl_PL","en"],"title":"{{appTitle}}","description":"{{appDescription}}","type":"application","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"dependencies":{"minUI5Version":"1.108.0","libs":{"sap.ui.core":{},"sap.m":{}}},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"ui5.walkthrough.i18n.i18n","supportedLocales":[""],"fallbackLocale":""}}},"rootView":{"viewName":"ui5.walkthrough.view.App","type":"XML","id":"app"}},"resources":{"css":[{"uri":"css/style.css"}]}}',
	"ui5/walkthrough/view/App.view.xml":'<mvc:View\r\n   controllerName="ui5.walkthrough.controller.App"\r\n   xmlns:mvc="sap.ui.core.mvc"\r\n   xmlns="sap.m"\r\n   displayBlock="true"><Shell><App><pages><Page title="{i18n>firstPageTitle}"><content><mvc:XMLView viewName="ui5.walkthrough.view.StartPanel"/></content></Page></pages></App></Shell></mvc:View>',
	"ui5/walkthrough/view/StartPanel.view.xml":'<mvc:View\r\n    controllerName="ui5.walkthrough.controller.StartPanel"\r\n   xmlns="sap.m"\r\n   xmlns:mvc="sap.ui.core.mvc"><Panel\r\n        class="sapUiResponsiveMargin"\r\n        width="auto"><content><Text text="{i18n>showTitleText}" class="sapUiSmallMargin element title"/><Button\r\n                text="{i18n>showDataButtonText}"\r\n                class="sapUiLargeMargin element"\r\n                press=".onShowClients"/><Table\r\n                  items="{\r\n                     path: \'/Customers\'\r\n                  }"><columns><Column><Text text="Nazwa firmy" /></Column><Column><Text text="Adres" /></Column><Column><Text text="Miasto" /></Column><Column><Text text="Kod pocztowy" /></Column><Column><Text text="Numer telefonu" /></Column></columns><items><ColumnListItem><cells><Text text="{CompanyName}" /><Text text="{Address}" /><Text text="{City}" /><Text text="{PostalCode}" /><Text text="{Phone}" /></cells></ColumnListItem></items></Table></content></Panel></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
